shortener/urls.py
from django.urls import path
from . import views

app_name = 'shortener'

urlpatterns = [
    path('', views.home, name='home'),
    path('links/', views.link_list, name='link_list'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
]

shortener/models.py
from django.db import models


class URL(models.Model):
    original_url = models.URLField()
    short_url = models.CharField(max_length=15, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

shortener/forms.py
from django import forms
from .models import URL


class URLForm(forms.ModelForm):
    class Meta:
        model = URL
        fields = ['original_url']

shortener/views.py
from django.shortcuts import render, redirect
from .models import URL
from .forms import URLForm
import random
import string

def generate_short_url():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=6))

def home(request):
    if request.method == 'POST':
        form = URLForm(request.POST)
        if form.is_valid():
            short_url = generate_short_url()
            url = form.save(commit=False)
            url.short_url = short_url
            url.save()
            return redirect('shortener:link_list')
    else:
        form = URLForm()
    return render(request, 'shortener/home.html', {'form': form})

def link_list(request):
    urls = URL.objects.all()
    return render(request, 'shortener/link_list.html', {'urls': urls})

shortener/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}URL Shortener{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'shortener:home' %}">URL Shortener</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shortener:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shortener:link_list' %}">Links</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

shortener/templates/shortener/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="mt-5">
    <h1>URL Shortener</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Shorten</button>
    </form>
</div>
{% endblock %}

shortener/templates/shortener/link_list.html
{% extends 'base.html' %}

{% block title %}Shortened Links{% endblock %}

{% block content %}
<div class="mt-5">
    <h1>Shortened Links</h1>
    <ul class="list-group">
        {% for url in urls %}
            <li class="list-group-item">
                <a href="{{ url.original_url }}" target="_blank">{{ url.original_url }}</a> -
                <a href="{{ url.short_url }}" target="_blank">{{ url.short_url }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}